name: Release changes to GitHub pages

on:
  push:
    branches:
      - main

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: c-hive/gha-npm-cache@v1

      - name: Install JS dependencies
        run: npm install

      - name: Release changes
        id: release_changes
        run: push-dir --dir=docs/www --branch=gh-pages
